# Generated by Django 4.1.4 on 2023-01-01 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_filesdata_delete_datamodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='filesdata',
            name='document',
            field=models.FileField(default=None, upload_to='documents/'),
        ),
    ]
